### ISSUE TITLE
wt 2.2

### ISSUE THREAD

**Issue by arbor95** [tronsmit/SA-history-4-webtrees#4]
in file module.php replace
line 102
    public function historicEventsAll(): Collection
with
    public function historicEventsAll(string $language_tag): Collection

**Comment by tronsmit** [comment]
Thanks Franz, I did not realise the changes in WT 2.2 were so pervasive.

I just want to figure out how to keep a 2.1.x release and see if it is now easier to have at least some default language translations. Should be simple, but I need a little time to do it
